### ISSUE TITLE
Unable to run rest-catalog with postgres instead of sqlite

### ISSUE THREAD

**Issue by hendoxc** [tabular-io/iceberg-rest-image#52]
Im running this docker compose file:
```yaml
---
version: "3"
services:
  iceberg-postgres-catalog:
    build:
      context: .
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: icebergcatalog
      POSTGRES_PASSWORD: icebergcatalog
      POSTGRES_DB: iceberg_catalog

  iceberg-rest-catalog:
    image: tabulario/iceberg-rest:latest
    ports:
      - "8181:8181"
    environment:
      CATALOG_URI: jdbc:postgres:/iceberg-postgres-catalog:5432/iceberg_catalog
      CATALOG_JDBC_USER: icebergcatalog
      CATALOG_JDBC_PASSWORD: icebergcatalog
      CATALOG_JDBC_DRIVER: org.postgresql.Driver
```

but apparently the postgres jdbc drivers aren't part of the image?
`No suitable driver found for jdbc:postgres:/iceberg-postgres-catalog:5432/iceberg_catalog`

should I just extend my own docker image and install the drivers?
